name: Cron Jobs

on:
  schedule:
    # cron for every day 8hours except sunday
    - cron: '0 */4 * * 1-6'
  workflow_dispatch:

env:
  GITARIST_TOKEN: ${{ secrets.GITARIST_TOKEN }}
  REPO: ${{ github.event.repository.name }}
  OWNER: ${{ github.repository_owner }}

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
      - uses: pnpm/action-setup
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "::set-output name=STORE_PATH::$(pnpm store path)"

      - uses: actions/cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm install
      - run: pnpm build
      - run: pnpm start
