name: Cron Jobs

on:
  schedule:
    # for every day N hours except sunday
    - cron: '0 */4 * * 1-6'
  workflow_dispatch:

env:
  GITARIST_TOKEN: ${{ secrets.GITARIST_TOKEN }}

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: echo "::set-output name=STORE_PATH::$(pnpm store path)"

      - uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm install
      - run: pnpm build
      - run: pnpm start

      # // --------------------------------
      # // --------------------------------
# jobs:
#   start:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 16
#           cache: yarn
#           cache-dependency-path: ./yarn.lock

#       - name: Get yarn cache directory
#         id: yarn-cache-dir
#         run: echo "::set-output name=STORE_PATH::$(yarn cache dir)"
#         # https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
#         # https://docs.github.com/en/actions/learn-github-actions/environment-variables#using-contexts-to-access-environment-variable-values
#         # run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

#       - uses: actions/cache@v3
#         id: restore-cache # use this to check for `cache-hit` (`steps.restore-cache.outputs.cache-hit != 'true'`)
#         with:
#           path: ${{ steps.yarn-cache-dir.outputs.STORE_PATH }}
#           key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-yarn-

#       - run: yarn install --frozen-lockfile
#       - run: yarn build
#       - run: yarn start
