name: Gitarist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * 1-6'

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npx gitarist run --owner $GITHUB_REPOSITORY_OWNER --repo ${{ github.event.repository.name }} --token ${{ secrets.GITARIST_TOKEN }}
