name: Security Check

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1-5'

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
